### PR TITLE
Change back button in profile of other users to use window.history.ba…

### PR DESCRIPTION
**Pull request by michael-lowe-nz**
…ck() instead of dispatching

Have a look at this, do you think it is ok?
I have kept the comment of what it used to be, just in case we later discover some bug

### CODE REVIEW

**Comment by gabrielamelian** [comment]
I'll pull and test now :)

**Comment by michael-lowe-nz** [comment]
Yay we are like real developers!

**Comment by gabrielamelian** [comment]
All working ok :+1:

**Review by gabrielamelian — COMMENTED** [review]
Tested and working as expected

**Pull request merged**
